### ISSUE TITLE
Not Python 3.4 compliant - NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by ghost** [makinacorpus/django-tracking-fields#1]
Hi,
When using a virtualenv in python 3.4, I got the following error from te admin page : 

``` python
  File "[...]/lib/python3.4/site-packages/tracking_fields/admin.py", line 82, in lookups
    lookups[value] = getattr(user_obj, 'username', unicode(user_obj))
NameError: name 'unicode' is not defined
```

when I drop `unicode()` all go well.

Regards

**Comment by Gagaro** [comment]
Thanks for the report. I should use six there.

Strange that travis didn't caught this one, I'll try to add a test for this one.

**Comment by Gagaro** [comment]
This is fixed but I can't release on pypi right now (https://status.python.org/).

**Comment by Gagaro** [comment]
1.0.6 released, thanks again for the report :+1: .
