### ISSUE TITLE
CommandError: Conflicting migrations detected (0002_auto_20160204_1213, 0002_auto_20160203_1048 in tracking_fields).

### ISSUE THREAD

**Issue by ghost** [makinacorpus/django-tracking-fields#2]
With the last update, django asked me to run migrate and then ...

``` python
./manage.py migrate
CommandError: Conflicting migrations detected (0002_auto_20160204_1213, 0002_auto_20160203_1048 in tracking_fields).
To fix them run 'python manage.py makemigrations --merge'
```

but the content of the both are the same.

**Comment by Gagaro** [comment]
Tracking fields only have one migration file (https://github.com/makinacorpus/django-tracking-fields/tree/master/tracking_fields/migrations).

Are those two files in tracking_field (and thus are missing and you created them with makemigrations)?

**Comment by ghost** [comment]
yes ... but the migration process does this by itself 

``` python
class Migration(migrations.Migration):

    dependencies = [
        ('tracking_fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'verbose_name': 'Tracking event',
                     'verbose_name_plural': 'Tracking events',
                     'ordering': ['-date']},
        ),
    ]
```

I dont know why.

So you can close the issue

**Comment by Gagaro** [comment]
I added the missing migration file to avoid any further issue. 

8fd265ca71a4bb19874f86edbf778b6315eff540

**Comment by Gagaro** [comment]
Thanks for the report :+1:
